import { GeistProvider, CssBaseline, Page, Themes } from '@geist-ui/react';
import Head from 'next/head';
import type { AppProps } from 'next/app';

import '@vetixy/circular-std';
import '@fontsource/karla';

import Container from '../components/Container';
import Logo from '../components/Logo';

import styles from './_app.module.css';
import Link from 'next/link';

const theme = Themes.createFromLight({
  type: 'main',
  palette: {
    error: '#f77f7f',
    errorLight: '#f77f7f',
    success: '#6acc97',
    secondary: '#3f5ea7',
  },
  font: {
    sans: 'CircularStd',
    mono: 'Karla',
  },
});

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <GeistProvider themeType="main" themes={[theme]}>
      <Head>
        <title>StartOut - Australia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CssBaseline />

      <main>
        <Component {...pageProps} />
      </main>

      {/* <Page size="medium">
        <Container>
          <Page.Content>
            <header>
              <Link href="/">
                <a className={styles.logo}>
                  <Logo />
                </a>
              </Link>
            </header>
          </Page.Content>
        </Container>
      </Page> */}
    </GeistProvider>
  );
}
export default MyApp;
