import { GeistProvider, CssBaseline, Page, Themes } from '@geist-ui/react';
import Head from 'next/head';
import type { AppProps } from 'next/app';

import '@vetixy/circular-std';
import '@fontsource/karla';

import '../styles/globals.css';

const theme = Themes.createFromLight({
  type: 'main',
  palette: {
    error: '#f77f7f',
    errorLight: '#f77f7f',
    success: '#6acc97',
    secondary: '#3f5ea7',
  },
  font: {
    sans: 'CircularStd',
    mono: 'Karla',
  },
});

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <GeistProvider themeType="main" themes={[theme]}>
      <Head>
        <title>StartOut - Australia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CssBaseline />

      <main>
        <Component {...pageProps} />
      </main>
    </GeistProvider>
  );
}
export default MyApp;
